spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}

jwt.SecretKey=${JWT_SECRET_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
cors.allowed-origins=${ALLOWED_ORIGINS}

springdoc.packages-to-scan=com.infosys.ParkEasy.controller
springdoc.paths-to-match=/**
logging.level.org.springdoc=DEBUG
logging.level.org.springdoc.api=DEBUG
logging.level.org.springdoc.core=DEBUG
logging.level.org.springframework.web=DEBUG